# Generated by Django 4.1.2 on 2022-10-28 08:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_me', models.CharField(max_length=500, null=True)),
                ('profile_image', models.FileField(upload_to='authors')),
                ('display_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('gen5der', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('show_gender', models.BooleanField(default='True')),
                ('show_email', models.BooleanField(default='True')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(default=datetime.datetime(2022, 10, 28, 15, 9, 57, 42791))),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=500)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.label')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented_by', models.CharField(max_length=50)),
                ('commented_at', models.DateTimeField(default=datetime.datetime(2022, 10, 28, 15, 9, 57, 42791))),
                ('description', models.CharField(max_length=500)),
                ('is_anonymous', models.BooleanField(default='True')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
